name: {{name}}
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  built_value: ^8.6.3
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  go_router: ^11.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  i18n_extension: ^9.0.2
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
